#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/clp
  
  autopep8 -ai -r src 
  autopep8 -air tests
  echo "not styling test_files/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
