[meta]
version = "0.1.0"

[project]
name = "clp"
package = "clp"
main_lang = "py"
version = "0.1.14"
version_date = "2018-03-21"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "utilities for computer language processing"
copyright = "2016-2017"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/clp"
state = "shared"
url = "https://jddixon.github.io/clp"

[py]
packages = [ "clp",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib", "xlattice_py",]
requirements = [ "pysha3", "setuptools",]
test_requirements = []
