# projConfig.toml for clp

[meta]
    version= '0.1.0'

[project]
    name = 'clp'             # external name = distribution name
    package = 'clp'             # internal name
    main_lang = 'py'
    version = '0.1.10'
    version_date = '2017-09-26'
    author = 'Jim Dixon'
    author_email = 'jdd@gmail.com'
    description='utilities for computer language processing'
    copyright = '2016-2017'
    dev_status = 'pre-alpha'
    license = 'mit'
    relpath = 'py/clp'
    state = 'shared'
    url = 'https://jddixon.github.io/clp'

[py]
    packages = ['clp']
    package_dir = ['src']
    test_dir = 'tests'
    py_modules = []
    scripts=[]
    ext_modules = []

    # sdReq output
    distshare = ['rnglib','xlattice_py']
    requirements=['pysha3','setuptools']
    test_requirements=[]

    # trove stuff is TBD


